### PR TITLE
split Lmod rpm in Lmod-core and Lmod

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by boegel** [comment]
lgtm

We should also upgrade to Lmod 8.6 soon-ish, since it includes a couple of nice changes.
But that should probably be a separate PR, since we want to ensure no breaking changes that affect typical usage on our systems has crept in (shouldn't be, but it wouldn't be the first time)...

**Comment by wpoely86** [comment]
Why the split?

The nice thing about Lmod 8.6 is that it finally has a proper config file so you could stop building your own and just use the epel one (with a config file).

**Comment by stdweird** [comment]
i need it installed on a system that uses SCl which requires properly working moduelcmd

**Comment by boegel** [comment]
@stdweird Do you have more info on what type of problems you're running into with the `modulecmd` wrapper that we put in place?

If we indeed need `modulecmd` available too, then using the Lmod from EPEL is going to remain to be a problem, unless we make an `Lmod-modulecmd` that depends on `Lmod` from EPEL...

**Review by boegel — APPROVED** [review]

**Pull request merged**
