### PR TITLE
add default for nagios-check-interval-threshold (HPC-6417)

### PR DESCRIPTION
**Pull request by wdpypere**

### CODE REVIEW

**Comment by boegel** [comment]
@wdpypere looks good, but missing JIRA ref?

**Comment by stdweird** [comment]
don't deploy this on loginnodes until they are at c73

**Comment by wdpypere** [comment]
@stdweird OK

**Comment by boegel** [comment]
@stdweird should be fine imho since this doesn't touch the cron job, but yeah, no reason to deploy this earlier

**Comment by stdweird** [comment]
quattor will happily restore the cron job

**Pull request merged**
