### PR TITLE
update to Lmod 7.7.5 & remove patch that is already included in it

### PR DESCRIPTION
**Pull request by boegel**
All tests in `vsc-testing/module` still pass when using this.

Lmod 7.7.3 has significantly more responsive tab completion, among other enhancements.

### CODE REVIEW

**Comment by boegel** [comment]
Tests fail with `Error: Unknown command: ugent`, no idea why that's happening all of a sudden, I don't see how the changes in this PR could trigger that.

@JensTimmerman Any idea what's going on here?

**Comment by boegel** [comment]
OK, figured it out, same problem as before with the directory in which the tests are being run containing spaces...

**Comment by boegel** [comment]
@stdweird Worth considering before we update workernodes & login nodes next week?

**Comment by stdweird** [comment]
build the rpm and all will be updated.

**Pull request merged**
