### PR TITLE
Update to Lmod 7 (HPC-6313) - WIP

### PR DESCRIPTION
**Pull request by wpoely86**
Do NOT merge yet.

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please mark as `[WIP]` until it's considered good to go

**Comment by boegel** [comment]
Holding this back: `module purge` is broken with Lmod 7.1.1

**Comment by wpoely86** [comment]
For reference: this is out of date. Look at https://github.com/hpcugent/Lmod-UGent/compare/master...wpoely86:lmod73

**Comment by boegel** [comment]
superseded by #25

**Pull request closed without merging**
