### PR TITLE
add modulecmd wrapper

### LINKED ISSUE #46: provide /usr/bin/modulecmd if possible
is it possible to ship a (small) wrapper `/usr/bin/modulecmd` that is either compatible with env-modules? not sure what it entails

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #46

### CODE REVIEW

**Comment by stdweird** [comment]
@boegel i think this works

**Comment by boegel** [comment]
Looks OK, to what extend has it been tested?

Also, how compatible with Environment Modules does it need to be?

**Comment by stdweird** [comment]
not tested at all, not sure why it is really needed (beyond satifisfying a dependency)

**Comment by boegel** [comment]
I guess you'll also need to enable execution permissions?

**Comment by stdweird** [comment]
the install permissions in the spec are ok, no?

**Comment by boegel** [comment]
Ah, right, the `755` is already there, sorry... Good to go then I guess.

**Pull request merged**
